[package]
version = "0.1.0"
name = "fib-script"
edition = "2021"

[[bin]]
name = "fib-demo"
path = "src/bin/main.rs"

[dependencies]
sp1-sdk = { version = "6.0.1", features = ["blocking", "native-gnark"] }
tempfile = "=3.27.0"
clap = { version = "4.0", features = ["derive"] }
hex = "0.4.3"

[build-dependencies]
sp1-build = { version = "6.0.1" }
